name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        env:
          MONGO_URI: mongodb://localhost:27017/testdb
          JWT_SECRET: testsecret
        run: npm test

  deploy:
    name: Deploy Application
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        if: github.ref == 'refs/heads/main'
        run: curl -X POST ${{ secrets.RAILWAY_DEPLOY_HOOK }}

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        run: |
          npm install -g vercel
          vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
